baseURL = 'https://ajanicij.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "anubis"
publishDir = "docs"

[menu]

[[menu.main]]
name = "Photography"
url = "/categories/photography"

[[menu.main]]
name = "About"
url = "/about"
weight = 2
